name: Setup SSH
description: setup ssh key in ~/.ssh/known_hosts

runs:
  using: composite
  steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE }}
      - name: Add known hosts
        shell: bash
        run: ssh-keyscan git.0verlight.com >> ~/.ssh/known_hosts