name: submodules
description: Clone submodules with ssh

runs:
  using: composite
  steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh_private_key }}
    - name: Add known hosts
      shell: bash
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan git.0verlight.com >> ~/.ssh/known_hosts
    - name: Clone submodules
      shell: bash
      run: git submodule update --init --recursive --remote